### PR TITLE
#10 fixed

### LINKED ISSUE #10: Fix receiving currency rate
Now https://free.currencyconverterapi.com/ requires API key to use.
It is necessary to implement API key usage or change currency rate provider

### PR DESCRIPTION
**Pull request by Katenkka**
Fixes #10

### CODE REVIEW

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java [hunk 1]
```diff
@@ -15,16 +19,24 @@
...
     @Test
-    public void extractCurrencyRateTest() throws IOException {
-        Float actualVal = underTest.extractCurrencyRate(testJsonRate, "USD_PHP");
-        Assert.assertEquals(53.310001, actualVal, 0.00001);
+    public void extractCurrencyRateTest() {
+        float actualVal = 0;
+
+        try {
+            actualVal = underTest.getRate(Currencies.USD, Currencies.CZK);
+        } catch (IOException e) {
```
Comment (ChmilevFA) [inline src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: Keep throws IOException for test methods, no need to catch it in this case

File: src/main/java/net/chmilevfa/telegram/bots/currency/state/handler/SecondCurrencyHandler.java [hunk 2]
```diff
@@ -67,16 +67,18 @@ private SendMessage onCurrentRateChosen(Message message, Language language) {
...
         try {
-            rate = currencyService.getRate(firstCurrency, secondCurrency);
+            float rate = currencyService.getRate(firstCurrency, secondCurrency);
+            responseText = String.format(
+                    localisationService.getString("currencyRate", language),
+                    firstCurrency, secondCurrency, String.format("%.2f", rate)
+            );
         } catch (IOException e) {
             logger.error("Error during requesting currency rate", e);
+            responseText = localisationService.getString("currencyServiceError", language);
```
Comment (ChmilevFA) [inline src/main/java/net/chmilevfa/telegram/bots/currency/state/handler/SecondCurrencyHandler.java]: Please add test to that case (IOException) SecondCurrencyHandlerTest.java it was missed earlier

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java [hunk 3]
```diff
@@ -15,16 +19,24 @@
...
 
     private CurrencyService underTest;
-    private final String testJsonRate = "{\"USD_PHP\":{\"val\":53.310001}}";
 
     @Before
-    public void init() {
-        underTest = new CurrencyService();
+    public void setUp() {
+        ConfigurableApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
+
```
Comment (ChmilevFA) [inline src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: Delete new line

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java [hunk 4]
```diff
@@ -15,16 +19,24 @@
...
 
     @Test
-    public void extractCurrencyRateTest() throws IOException {
-        Float actualVal = underTest.extractCurrencyRate(testJsonRate, "USD_PHP");
-        Assert.assertEquals(53.310001, actualVal, 0.00001);
+    public void extractCurrencyRateTest() {
+        float actualVal = 0;
+
+        try {
+            actualVal = underTest.getRate(Currencies.USD, Currencies.CZK);
```
Comment (ChmilevFA) [inline src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: It's not integration test, there is no need to test service. You can mock it for Unit tests.
Also keep extractCurrencyRateTest please, please refactor your current test to separate one.

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java [hunk 5]
```diff
@@ -15,16 +19,24 @@
 public class CurrencyServiceTest {
 
     private CurrencyService underTest;
-    private final String testJsonRate = "{\"USD_PHP\":{\"val\":53.310001}}";
 
     @Before
-    public void init() {
-        underTest = new CurrencyService();
+    public void setUp() {
+        ConfigurableApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
```
Comment (ChmilevFA) [inline src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: There is no need to use reapApp config

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java (hunk 1 above)
Comment (Katenkka) [reply src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: Fixed

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java (hunk 3 above)
Comment (Katenkka) [reply src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: Fixed

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java (hunk 5 above)
Comment (Katenkka) [reply src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: Fixed

File: src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java (hunk 4 above)
Comment (Katenkka) [reply src/test/java/net/chmilevfa/telegram/bots/currency/service/CurrencyServiceTest.java]: Fixed

File: src/main/java/net/chmilevfa/telegram/bots/currency/state/handler/SecondCurrencyHandler.java (hunk 2 above)
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/state/handler/SecondCurrencyHandler.java]: Fixed

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+
+    /** Mapper for reading JSON */
+    private static final ObjectMapper MAPPER = new ObjectMapper();
+
+    /** ApiKey for external service */
+    @Value("${freecurrencyconverter.apiKey}")
+    private String apiKey;
+
+    /**
+     * Get rate for pair of currencies.
```
Comment (ChmilevFA) [inline src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: You can move this javadoc to the interface. Override annotation is enough to point to this comment.

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+     * @return current rate for from/to.
+     */
+    @Override
+    public float getRate(Currencies from, Currencies to) throws IOException {
+        String currencyArg = from.name() + "_" + to.name();
+        return extractCurrencyRate(fetchExternalContent(currencyArg), currencyArg);
+    }
+
+    /**
+     *
```
Comment (ChmilevFA) [inline src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: Please delete one empty line or add comment what is this method suppose to do.

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+     * @param currencyArg currencies names joined by "_"
+     * @return content from external website
+     */
+    String fetchExternalContent(String currencyArg) throws IOException {
```
Comment (ChmilevFA) [inline src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: If you can not refactor it to make this method private, please add VisibleForTesting annotation

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+
+            while ((inputLine = in.readLine()) != null) {
+                contentBuilder.append(inputLine);
+            }
+        }
+
+        return contentBuilder.toString();
+    }
+
+    float extractCurrencyRate(String data, String currencyArg) throws IOException {
```
Comment (ChmilevFA) [inline src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: If you can not refactor it to make this method private, please add VisibleForTesting annotation

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+
+    /** URL of exchange rate service */
+    private final static String CURRENCY_CONVERTER_URL =
+            "https://free.currencyconverterapi.com/api/v6/convert?q=%s&compact=y&apiKey=%s";
+
+    /** Mapper for reading JSON */
+    private static final ObjectMapper MAPPER = new ObjectMapper();
+
+    /** ApiKey for external service */
+    @Value("${freecurrencyconverter.apiKey}")
```
[the remark this answers is not in the document]
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: How can I then instance this Service in test? Just call with a random string?

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java (hunk 8 above)
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: I cannot do them private exactly because they are used in testing

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: Okay, that's exactly what I did

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/CurrencyService.java [hunk 11]
```diff
@@ -1,64 +1,9 @@
...
-        }
-
-        return extractCurrencyRate(content.toString(), currencyArg);
-    }
-
-    float extractCurrencyRate(String data, String currencyArg) throws IOException {
-        String textValue = MAPPER.readTree(data).at("/" + currencyArg + "/val").asText();
-        return Float.parseFloat(textValue);
-    }
+public interface CurrencyService {
```
[the remark this answers is not in the document]
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/CurrencyService.java]: Done

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java (hunk 6 above)
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: Done

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java (hunk 7 above)
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: Done

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java (hunk 9 above)
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: Added annotation

File: src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java (hunk 8 above)
Comment (Katenkka) [reply src/main/java/net/chmilevfa/telegram/bots/currency/service/impl/FreeCurrencyConverterApiService.java]: Added annotation

File: src/main/resources/currencyservice.properties [hunk 12]
```diff
@@ -0,0 +1 @@
+freecurrencyconverter.apiKey=[apiKey]
```
Comment (ChmilevFA) [inline src/main/resources/currencyservice.properties]: 1. Use application.properties instead of creating new config
2. Add new field to BotConfig
3. Inject BotConfig instead of value and retrieve key from that config

Comment (Katenkka) [reply src/main/resources/currencyservice.properties]: I think these properties should be separated

Comment (ChmilevFA) [reply src/main/resources/currencyservice.properties]: Why?

Comment (Katenkka) [reply src/main/resources/currencyservice.properties]: Because it's not directly connected to bot config, it's more of config for a different, external service

Comment (Katenkka) [reply src/main/resources/currencyservice.properties]: So what are we gonna do?

Comment (ChmilevFA) [reply src/main/resources/currencyservice.properties]: 1. We already have application.properties which contains keys for external services, from this point of view where is no need to create separate properties for every key.
2. Also current architecture suppose to have and use all these properties using specifyed bean of BotConfig class. It allows us: a.) to get all configurations from one predictable place. b.) do not read directly from target class using @PropertySource("classpath:currencyservice.properties")

Probably using separate .properties files makes sense for big application with huge amount of parameters, but our app still small and have only few external parameters.

Comment (Katenkka) [reply src/main/resources/currencyservice.properties]: Okay. Fixed that
